services:
  postgres:
    image: postgres:15 # imagem utilizada
    container_name: postgres # nome do container
    restart: always
    environment:
      POSTGRES_USER: admin # user  do banco
      POSTGRES_PASSWORD: admin # Senha do banco
      POSTGRES_DB: admin # nome do banco
    ports:
      - "5432:5432" # porta do container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # para rodar a migration
      - ./Arquivos:/arquivos # onde estao nossos arquivos
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Usuario pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # senha pgAdim
    ports:
      - "5050:80" # porta do navegado onde vamos acessar a interface
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-server.json:/pgadmin4/servers.json 
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin-data: